/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IndianMutualFundsAnalysisSwpRouteImport } from './routes/indian-mutual-funds-analysis/swp'
import { Route as IndianMutualFundsAnalysisSipRouteImport } from './routes/indian-mutual-funds-analysis/sip'
import { Route as IndianMutualFundsAnalysisNavRouteImport } from './routes/indian-mutual-funds-analysis/nav'
import { Route as IndianMutualFundsAnalysisCagrRouteImport } from './routes/indian-mutual-funds-analysis/cagr'
import { Route as CalculatorsSwpRouteImport } from './routes/calculators/swp'
import { Route as CalculatorsSipSwpRouteImport } from './routes/calculators/sip-swp'
import { Route as CalculatorsSipRouteImport } from './routes/calculators/sip'
import { Route as CalculatorsRecurringDepositRouteImport } from './routes/calculators/recurring-deposit'
import { Route as CalculatorsFixedDepositRouteImport } from './routes/calculators/fixed-deposit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IndianMutualFundsAnalysisSwpRoute =
  IndianMutualFundsAnalysisSwpRouteImport.update({
    id: '/indian-mutual-funds-analysis/swp',
    path: '/indian-mutual-funds-analysis/swp',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndianMutualFundsAnalysisSipRoute =
  IndianMutualFundsAnalysisSipRouteImport.update({
    id: '/indian-mutual-funds-analysis/sip',
    path: '/indian-mutual-funds-analysis/sip',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndianMutualFundsAnalysisNavRoute =
  IndianMutualFundsAnalysisNavRouteImport.update({
    id: '/indian-mutual-funds-analysis/nav',
    path: '/indian-mutual-funds-analysis/nav',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndianMutualFundsAnalysisCagrRoute =
  IndianMutualFundsAnalysisCagrRouteImport.update({
    id: '/indian-mutual-funds-analysis/cagr',
    path: '/indian-mutual-funds-analysis/cagr',
    getParentRoute: () => rootRouteImport,
  } as any)
const CalculatorsSwpRoute = CalculatorsSwpRouteImport.update({
  id: '/calculators/swp',
  path: '/calculators/swp',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorsSipSwpRoute = CalculatorsSipSwpRouteImport.update({
  id: '/calculators/sip-swp',
  path: '/calculators/sip-swp',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorsSipRoute = CalculatorsSipRouteImport.update({
  id: '/calculators/sip',
  path: '/calculators/sip',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorsRecurringDepositRoute =
  CalculatorsRecurringDepositRouteImport.update({
    id: '/calculators/recurring-deposit',
    path: '/calculators/recurring-deposit',
    getParentRoute: () => rootRouteImport,
  } as any)
const CalculatorsFixedDepositRoute = CalculatorsFixedDepositRouteImport.update({
  id: '/calculators/fixed-deposit',
  path: '/calculators/fixed-deposit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calculators/fixed-deposit': typeof CalculatorsFixedDepositRoute
  '/calculators/recurring-deposit': typeof CalculatorsRecurringDepositRoute
  '/calculators/sip': typeof CalculatorsSipRoute
  '/calculators/sip-swp': typeof CalculatorsSipSwpRoute
  '/calculators/swp': typeof CalculatorsSwpRoute
  '/indian-mutual-funds-analysis/cagr': typeof IndianMutualFundsAnalysisCagrRoute
  '/indian-mutual-funds-analysis/nav': typeof IndianMutualFundsAnalysisNavRoute
  '/indian-mutual-funds-analysis/sip': typeof IndianMutualFundsAnalysisSipRoute
  '/indian-mutual-funds-analysis/swp': typeof IndianMutualFundsAnalysisSwpRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calculators/fixed-deposit': typeof CalculatorsFixedDepositRoute
  '/calculators/recurring-deposit': typeof CalculatorsRecurringDepositRoute
  '/calculators/sip': typeof CalculatorsSipRoute
  '/calculators/sip-swp': typeof CalculatorsSipSwpRoute
  '/calculators/swp': typeof CalculatorsSwpRoute
  '/indian-mutual-funds-analysis/cagr': typeof IndianMutualFundsAnalysisCagrRoute
  '/indian-mutual-funds-analysis/nav': typeof IndianMutualFundsAnalysisNavRoute
  '/indian-mutual-funds-analysis/sip': typeof IndianMutualFundsAnalysisSipRoute
  '/indian-mutual-funds-analysis/swp': typeof IndianMutualFundsAnalysisSwpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calculators/fixed-deposit': typeof CalculatorsFixedDepositRoute
  '/calculators/recurring-deposit': typeof CalculatorsRecurringDepositRoute
  '/calculators/sip': typeof CalculatorsSipRoute
  '/calculators/sip-swp': typeof CalculatorsSipSwpRoute
  '/calculators/swp': typeof CalculatorsSwpRoute
  '/indian-mutual-funds-analysis/cagr': typeof IndianMutualFundsAnalysisCagrRoute
  '/indian-mutual-funds-analysis/nav': typeof IndianMutualFundsAnalysisNavRoute
  '/indian-mutual-funds-analysis/sip': typeof IndianMutualFundsAnalysisSipRoute
  '/indian-mutual-funds-analysis/swp': typeof IndianMutualFundsAnalysisSwpRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calculators/fixed-deposit'
    | '/calculators/recurring-deposit'
    | '/calculators/sip'
    | '/calculators/sip-swp'
    | '/calculators/swp'
    | '/indian-mutual-funds-analysis/cagr'
    | '/indian-mutual-funds-analysis/nav'
    | '/indian-mutual-funds-analysis/sip'
    | '/indian-mutual-funds-analysis/swp'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calculators/fixed-deposit'
    | '/calculators/recurring-deposit'
    | '/calculators/sip'
    | '/calculators/sip-swp'
    | '/calculators/swp'
    | '/indian-mutual-funds-analysis/cagr'
    | '/indian-mutual-funds-analysis/nav'
    | '/indian-mutual-funds-analysis/sip'
    | '/indian-mutual-funds-analysis/swp'
  id:
    | '__root__'
    | '/'
    | '/calculators/fixed-deposit'
    | '/calculators/recurring-deposit'
    | '/calculators/sip'
    | '/calculators/sip-swp'
    | '/calculators/swp'
    | '/indian-mutual-funds-analysis/cagr'
    | '/indian-mutual-funds-analysis/nav'
    | '/indian-mutual-funds-analysis/sip'
    | '/indian-mutual-funds-analysis/swp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalculatorsFixedDepositRoute: typeof CalculatorsFixedDepositRoute
  CalculatorsRecurringDepositRoute: typeof CalculatorsRecurringDepositRoute
  CalculatorsSipRoute: typeof CalculatorsSipRoute
  CalculatorsSipSwpRoute: typeof CalculatorsSipSwpRoute
  CalculatorsSwpRoute: typeof CalculatorsSwpRoute
  IndianMutualFundsAnalysisCagrRoute: typeof IndianMutualFundsAnalysisCagrRoute
  IndianMutualFundsAnalysisNavRoute: typeof IndianMutualFundsAnalysisNavRoute
  IndianMutualFundsAnalysisSipRoute: typeof IndianMutualFundsAnalysisSipRoute
  IndianMutualFundsAnalysisSwpRoute: typeof IndianMutualFundsAnalysisSwpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indian-mutual-funds-analysis/swp': {
      id: '/indian-mutual-funds-analysis/swp'
      path: '/indian-mutual-funds-analysis/swp'
      fullPath: '/indian-mutual-funds-analysis/swp'
      preLoaderRoute: typeof IndianMutualFundsAnalysisSwpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indian-mutual-funds-analysis/sip': {
      id: '/indian-mutual-funds-analysis/sip'
      path: '/indian-mutual-funds-analysis/sip'
      fullPath: '/indian-mutual-funds-analysis/sip'
      preLoaderRoute: typeof IndianMutualFundsAnalysisSipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indian-mutual-funds-analysis/nav': {
      id: '/indian-mutual-funds-analysis/nav'
      path: '/indian-mutual-funds-analysis/nav'
      fullPath: '/indian-mutual-funds-analysis/nav'
      preLoaderRoute: typeof IndianMutualFundsAnalysisNavRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indian-mutual-funds-analysis/cagr': {
      id: '/indian-mutual-funds-analysis/cagr'
      path: '/indian-mutual-funds-analysis/cagr'
      fullPath: '/indian-mutual-funds-analysis/cagr'
      preLoaderRoute: typeof IndianMutualFundsAnalysisCagrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculators/swp': {
      id: '/calculators/swp'
      path: '/calculators/swp'
      fullPath: '/calculators/swp'
      preLoaderRoute: typeof CalculatorsSwpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculators/sip-swp': {
      id: '/calculators/sip-swp'
      path: '/calculators/sip-swp'
      fullPath: '/calculators/sip-swp'
      preLoaderRoute: typeof CalculatorsSipSwpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculators/sip': {
      id: '/calculators/sip'
      path: '/calculators/sip'
      fullPath: '/calculators/sip'
      preLoaderRoute: typeof CalculatorsSipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculators/recurring-deposit': {
      id: '/calculators/recurring-deposit'
      path: '/calculators/recurring-deposit'
      fullPath: '/calculators/recurring-deposit'
      preLoaderRoute: typeof CalculatorsRecurringDepositRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculators/fixed-deposit': {
      id: '/calculators/fixed-deposit'
      path: '/calculators/fixed-deposit'
      fullPath: '/calculators/fixed-deposit'
      preLoaderRoute: typeof CalculatorsFixedDepositRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalculatorsFixedDepositRoute: CalculatorsFixedDepositRoute,
  CalculatorsRecurringDepositRoute: CalculatorsRecurringDepositRoute,
  CalculatorsSipRoute: CalculatorsSipRoute,
  CalculatorsSipSwpRoute: CalculatorsSipSwpRoute,
  CalculatorsSwpRoute: CalculatorsSwpRoute,
  IndianMutualFundsAnalysisCagrRoute: IndianMutualFundsAnalysisCagrRoute,
  IndianMutualFundsAnalysisNavRoute: IndianMutualFundsAnalysisNavRoute,
  IndianMutualFundsAnalysisSipRoute: IndianMutualFundsAnalysisSipRoute,
  IndianMutualFundsAnalysisSwpRoute: IndianMutualFundsAnalysisSwpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
