/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InvestmentAnalysisSwpRouteImport } from './routes/investment-analysis/swp'
import { Route as InvestmentAnalysisSipRouteImport } from './routes/investment-analysis/sip'
import { Route as InvestmentAnalysisPriceHistoryRouteImport } from './routes/investment-analysis/price-history'
import { Route as InvestmentAnalysisCagrRouteImport } from './routes/investment-analysis/cagr'
import { Route as CalculatorsSwpRouteImport } from './routes/calculators/swp'
import { Route as CalculatorsSipSwpRouteImport } from './routes/calculators/sip-swp'
import { Route as CalculatorsSipRouteImport } from './routes/calculators/sip'
import { Route as CalculatorsRecurringDepositRouteImport } from './routes/calculators/recurring-deposit'
import { Route as CalculatorsFixedDepositRouteImport } from './routes/calculators/fixed-deposit'
import { Route as ItrScheduleFaA3RouteImport } from './routes/itr/schedule-fa/a3'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestmentAnalysisSwpRoute = InvestmentAnalysisSwpRouteImport.update({
  id: '/investment-analysis/swp',
  path: '/investment-analysis/swp',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestmentAnalysisSipRoute = InvestmentAnalysisSipRouteImport.update({
  id: '/investment-analysis/sip',
  path: '/investment-analysis/sip',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestmentAnalysisPriceHistoryRoute =
  InvestmentAnalysisPriceHistoryRouteImport.update({
    id: '/investment-analysis/price-history',
    path: '/investment-analysis/price-history',
    getParentRoute: () => rootRouteImport,
  } as any)
const InvestmentAnalysisCagrRoute = InvestmentAnalysisCagrRouteImport.update({
  id: '/investment-analysis/cagr',
  path: '/investment-analysis/cagr',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorsSwpRoute = CalculatorsSwpRouteImport.update({
  id: '/calculators/swp',
  path: '/calculators/swp',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorsSipSwpRoute = CalculatorsSipSwpRouteImport.update({
  id: '/calculators/sip-swp',
  path: '/calculators/sip-swp',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorsSipRoute = CalculatorsSipRouteImport.update({
  id: '/calculators/sip',
  path: '/calculators/sip',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorsRecurringDepositRoute =
  CalculatorsRecurringDepositRouteImport.update({
    id: '/calculators/recurring-deposit',
    path: '/calculators/recurring-deposit',
    getParentRoute: () => rootRouteImport,
  } as any)
const CalculatorsFixedDepositRoute = CalculatorsFixedDepositRouteImport.update({
  id: '/calculators/fixed-deposit',
  path: '/calculators/fixed-deposit',
  getParentRoute: () => rootRouteImport,
} as any)
const ItrScheduleFaA3Route = ItrScheduleFaA3RouteImport.update({
  id: '/itr/schedule-fa/a3',
  path: '/itr/schedule-fa/a3',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calculators/fixed-deposit': typeof CalculatorsFixedDepositRoute
  '/calculators/recurring-deposit': typeof CalculatorsRecurringDepositRoute
  '/calculators/sip': typeof CalculatorsSipRoute
  '/calculators/sip-swp': typeof CalculatorsSipSwpRoute
  '/calculators/swp': typeof CalculatorsSwpRoute
  '/investment-analysis/cagr': typeof InvestmentAnalysisCagrRoute
  '/investment-analysis/price-history': typeof InvestmentAnalysisPriceHistoryRoute
  '/investment-analysis/sip': typeof InvestmentAnalysisSipRoute
  '/investment-analysis/swp': typeof InvestmentAnalysisSwpRoute
  '/itr/schedule-fa/a3': typeof ItrScheduleFaA3Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calculators/fixed-deposit': typeof CalculatorsFixedDepositRoute
  '/calculators/recurring-deposit': typeof CalculatorsRecurringDepositRoute
  '/calculators/sip': typeof CalculatorsSipRoute
  '/calculators/sip-swp': typeof CalculatorsSipSwpRoute
  '/calculators/swp': typeof CalculatorsSwpRoute
  '/investment-analysis/cagr': typeof InvestmentAnalysisCagrRoute
  '/investment-analysis/price-history': typeof InvestmentAnalysisPriceHistoryRoute
  '/investment-analysis/sip': typeof InvestmentAnalysisSipRoute
  '/investment-analysis/swp': typeof InvestmentAnalysisSwpRoute
  '/itr/schedule-fa/a3': typeof ItrScheduleFaA3Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calculators/fixed-deposit': typeof CalculatorsFixedDepositRoute
  '/calculators/recurring-deposit': typeof CalculatorsRecurringDepositRoute
  '/calculators/sip': typeof CalculatorsSipRoute
  '/calculators/sip-swp': typeof CalculatorsSipSwpRoute
  '/calculators/swp': typeof CalculatorsSwpRoute
  '/investment-analysis/cagr': typeof InvestmentAnalysisCagrRoute
  '/investment-analysis/price-history': typeof InvestmentAnalysisPriceHistoryRoute
  '/investment-analysis/sip': typeof InvestmentAnalysisSipRoute
  '/investment-analysis/swp': typeof InvestmentAnalysisSwpRoute
  '/itr/schedule-fa/a3': typeof ItrScheduleFaA3Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calculators/fixed-deposit'
    | '/calculators/recurring-deposit'
    | '/calculators/sip'
    | '/calculators/sip-swp'
    | '/calculators/swp'
    | '/investment-analysis/cagr'
    | '/investment-analysis/price-history'
    | '/investment-analysis/sip'
    | '/investment-analysis/swp'
    | '/itr/schedule-fa/a3'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calculators/fixed-deposit'
    | '/calculators/recurring-deposit'
    | '/calculators/sip'
    | '/calculators/sip-swp'
    | '/calculators/swp'
    | '/investment-analysis/cagr'
    | '/investment-analysis/price-history'
    | '/investment-analysis/sip'
    | '/investment-analysis/swp'
    | '/itr/schedule-fa/a3'
  id:
    | '__root__'
    | '/'
    | '/calculators/fixed-deposit'
    | '/calculators/recurring-deposit'
    | '/calculators/sip'
    | '/calculators/sip-swp'
    | '/calculators/swp'
    | '/investment-analysis/cagr'
    | '/investment-analysis/price-history'
    | '/investment-analysis/sip'
    | '/investment-analysis/swp'
    | '/itr/schedule-fa/a3'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalculatorsFixedDepositRoute: typeof CalculatorsFixedDepositRoute
  CalculatorsRecurringDepositRoute: typeof CalculatorsRecurringDepositRoute
  CalculatorsSipRoute: typeof CalculatorsSipRoute
  CalculatorsSipSwpRoute: typeof CalculatorsSipSwpRoute
  CalculatorsSwpRoute: typeof CalculatorsSwpRoute
  InvestmentAnalysisCagrRoute: typeof InvestmentAnalysisCagrRoute
  InvestmentAnalysisPriceHistoryRoute: typeof InvestmentAnalysisPriceHistoryRoute
  InvestmentAnalysisSipRoute: typeof InvestmentAnalysisSipRoute
  InvestmentAnalysisSwpRoute: typeof InvestmentAnalysisSwpRoute
  ItrScheduleFaA3Route: typeof ItrScheduleFaA3Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investment-analysis/swp': {
      id: '/investment-analysis/swp'
      path: '/investment-analysis/swp'
      fullPath: '/investment-analysis/swp'
      preLoaderRoute: typeof InvestmentAnalysisSwpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investment-analysis/sip': {
      id: '/investment-analysis/sip'
      path: '/investment-analysis/sip'
      fullPath: '/investment-analysis/sip'
      preLoaderRoute: typeof InvestmentAnalysisSipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investment-analysis/price-history': {
      id: '/investment-analysis/price-history'
      path: '/investment-analysis/price-history'
      fullPath: '/investment-analysis/price-history'
      preLoaderRoute: typeof InvestmentAnalysisPriceHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investment-analysis/cagr': {
      id: '/investment-analysis/cagr'
      path: '/investment-analysis/cagr'
      fullPath: '/investment-analysis/cagr'
      preLoaderRoute: typeof InvestmentAnalysisCagrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculators/swp': {
      id: '/calculators/swp'
      path: '/calculators/swp'
      fullPath: '/calculators/swp'
      preLoaderRoute: typeof CalculatorsSwpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculators/sip-swp': {
      id: '/calculators/sip-swp'
      path: '/calculators/sip-swp'
      fullPath: '/calculators/sip-swp'
      preLoaderRoute: typeof CalculatorsSipSwpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculators/sip': {
      id: '/calculators/sip'
      path: '/calculators/sip'
      fullPath: '/calculators/sip'
      preLoaderRoute: typeof CalculatorsSipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculators/recurring-deposit': {
      id: '/calculators/recurring-deposit'
      path: '/calculators/recurring-deposit'
      fullPath: '/calculators/recurring-deposit'
      preLoaderRoute: typeof CalculatorsRecurringDepositRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculators/fixed-deposit': {
      id: '/calculators/fixed-deposit'
      path: '/calculators/fixed-deposit'
      fullPath: '/calculators/fixed-deposit'
      preLoaderRoute: typeof CalculatorsFixedDepositRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/itr/schedule-fa/a3': {
      id: '/itr/schedule-fa/a3'
      path: '/itr/schedule-fa/a3'
      fullPath: '/itr/schedule-fa/a3'
      preLoaderRoute: typeof ItrScheduleFaA3RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalculatorsFixedDepositRoute: CalculatorsFixedDepositRoute,
  CalculatorsRecurringDepositRoute: CalculatorsRecurringDepositRoute,
  CalculatorsSipRoute: CalculatorsSipRoute,
  CalculatorsSipSwpRoute: CalculatorsSipSwpRoute,
  CalculatorsSwpRoute: CalculatorsSwpRoute,
  InvestmentAnalysisCagrRoute: InvestmentAnalysisCagrRoute,
  InvestmentAnalysisPriceHistoryRoute: InvestmentAnalysisPriceHistoryRoute,
  InvestmentAnalysisSipRoute: InvestmentAnalysisSipRoute,
  InvestmentAnalysisSwpRoute: InvestmentAnalysisSwpRoute,
  ItrScheduleFaA3Route: ItrScheduleFaA3Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
